/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.ScrollPane;
import javax.swing.ImageIcon;

/**
 *
 * @author Ariel
 */
public class MarcoContenedor extends javax.swing.JFrame{
  
    private PanelArbol panelArbol;
    
    private PanelContenedor panelContenedor;
    private ScrollPane srollContenedor;
    /**
     * Creates new form MarcoContenedor
     */
    public MarcoContenedor() {
        
        
        //Función de inicialización de componentes. Netbeans la coloca por defecto
        initComponents();
        try {
            //Icono de la aplicacion
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
        } catch (Exception e) {
        }
        
        
        //Colocamos el nuevo tipo de layout que queremos que tenga nuestro JFrame
        this.setLayout(new BorderLayout());
        
        
         //Hacemos que el JFrame tenga el tamaño de todos sus elementos
         this.pack();
        
        
        //Ubica el JFrame en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jpPrincipal = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        PanelArbol panelArbol= new PanelArbol();
        jpArbol = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSuma = new javax.swing.JMenuItem();
        jmiResta = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Mercadito");
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jpPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpPrincipal.setMaximumSize(new java.awt.Dimension(1043, 770));
        jpPrincipal.setMinimumSize(new java.awt.Dimension(1043, 770));
        jpPrincipal.setPreferredSize(new java.awt.Dimension(1043, 770));

        jpContenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpContenedor.setMaximumSize(new java.awt.Dimension(740, 740));
        jpContenedor.setMinimumSize(new java.awt.Dimension(740, 740));
        jpContenedor.setPreferredSize(new java.awt.Dimension(740, 740));
        jpContenedor.setLayout(null);

        jpArbol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpArbol.setMaximumSize(new java.awt.Dimension(240, 800));
        jpArbol.setMinimumSize(new java.awt.Dimension(240, 700));
        jpArbol.setPreferredSize(new java.awt.Dimension(240, 700));
        jpArbol.setRequestFocusEnabled(false);
        jpArbol.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jpArbolAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jpArbol.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jpArbolPropertyChange(evt);
            }
        });
        jpArbol.setLayout(null);

        jpArbol.add(panelArbol);
        repaint();

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(789, Short.MAX_VALUE)))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        getContentPane().add(jpPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        jmiSuma.setText("Nueva Suma");
        jMenu1.add(jmiSuma);

        jmiResta.setText("Nueva Resta");
        jMenu1.add(jmiResta);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/24x24/delete.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpArbolAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jpArbolAncestorAdded
              
       panelArbol = new PanelArbol();
       panelArbol.setSize(230, 690);
       panelArbol.setLocation(6, 6);
 

       
       jpArbol.removeAll();
       jpArbol.add(panelArbol, BorderLayout.NORTH);
       jpArbol.repaint();
       
       panelContenedor = new PanelContenedor();
       panelContenedor.setSize(730, 690);
       panelContenedor.setLocation(6, 6);
       
       
       jpContenedor.add(panelContenedor, BorderLayout.NORTH);
       jpContenedor.repaint();
       
    }//GEN-LAST:event_jpArbolAncestorAdded

    private void jpArbolPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jpArbolPropertyChange
        jpContenedor.repaint();
        jpArbol.repaint();
    }//GEN-LAST:event_jpArbolPropertyChange

   
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiResta;
    private javax.swing.JMenuItem jmiSuma;
    public static javax.swing.JPanel jpArbol;
    public static javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpPrincipal;
    // End of variables declaration//GEN-END:variables

   
}
