/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;


/**
 *
 * @author Ariel
 */
public class PanelContenedor extends javax.swing.JPanel{

    /**
     * Creates new form PanelHijoSuma
     */
    public PanelContenedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlblApellido2 = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(700, 690));
        setMinimumSize(new java.awt.Dimension(700, 690));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(null);

        jlblNombre.setText("Nombre:");
        add(jlblNombre);
        jlblNombre.setBounds(40, 30, 41, 14);

        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
        });
        add(jtfNombre);
        jtfNombre.setBounds(90, 30, 99, 20);

        jlblApellido2.setText("Apellido:");
        add(jlblApellido2);
        jlblApellido2.setBounds(40, 70, 41, 14);
        add(jtfApellido);
        jtfApellido.setBounds(90, 70, 99, 20);

        getAccessibleContext().setAccessibleName("PanelContenedor");
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        //Asignamos el texto del textBox a una variable Integer
        String nombre = this.jtfNombre.getText();
        String apellido = this.jtfApellido.getText();
        
    }//GEN-LAST:event_jtfNombreKeyReleased

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        this.repaint();
    }//GEN-LAST:event_formPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblApellido2;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

  
}
