/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Ariel
 */
public class PanelArbol extends javax.swing.JPanel {

    /**
     * Creates new form PanelArbol
     */
    public PanelArbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTree1 = new javax.swing.JTree();

        setMaximumSize(new java.awt.Dimension(230, 670));
        setMinimumSize(new java.awt.Dimension(230, 670));
        setPreferredSize(new java.awt.Dimension(230, 670));
        setLayout(null);

        jTree1.setAlignmentX(0.0F);
        jTree1.setAlignmentY(0.0F);
        jTree1.setMaximumSize(new java.awt.Dimension(230, 670));
        jTree1.setMinimumSize(new java.awt.Dimension(230, 670));
        add(jTree1);
        jTree1.setBounds(0, 0, 240, 700);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
